# require 'boethius/metadata'
require 'boethius/xmlenv'
require 'boethius/filenames'
require 'boethius/helpers'
require 'boethius/formatting'

module Boethius

  class Tex < Hash

    BOILERPLATE = <<~IN
      %LuaTeX

      % This file has been generated by Boethius,
      % which is freely distributed under the AGPLv3.
      % Copyright 2017, Gerard Keiser
    IN

    def generate
      filename = "#{File.join(Boethius::PROJECT_DIR, self[:id].to_s)}"
      @source = Source.new("#{filename}.tex", "w")
      @source.puts BOILERPLATE
      @source.add_space
      # @source.puts self.metadata
      # @source.add_space
      @source.puts self.xmlenv
      @source.add_space
      @source.puts self.formatting
      @source.add_space
      @source.puts '\starttext'
      @source.add_space
      @source.puts self.filenames
      @source.puts '\stoptext'
      return @source
    ensure
      @source.close
    end

  end

end
